version: "3"
services:
  nginx:
    image: nginx:1.16-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/certificates:/var/www/sc-market.space/certificates
      - ./config/nginx:/etc/nginx/conf.d

    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  web:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
      - "7000:7000"
    restart: unless-stopped

  discord:
    build: ../SCMarketBot
    env_file: .env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: scmarket
      POSTGRES_DB: scmarket
      POSTGRES_PASSWORD: scmarket
    volumes:
      - ./config/postgres/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /var/lib/dashboard/postgresql/data_prodcopy:/var/lib/postgresql/data
    ports:
      - "5432:5432"
