version: "3"
services:
  nginx:
    image: nginx:1.16-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/certificates:/var/www/sc-market.space/certificates
      - ./config/nginx:/etc/nginx/conf.d

    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  web:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
      - "7000:7000"
    restart: always
    healthcheck:
      test: curl -sS http://127.0.0.1:8080/api/market/stats || exit 1
      interval: 30s
      timeout: 1s
      retries: 3

  discord:
    build: ../SCMarketBot
    env_file: .env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: scmarket
      POSTGRES_DB: scmarket
      POSTGRES_PASSWORD: scmarket
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
