version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "7000:7000"
    networks:
      - default
    restart: unless-stopped

  discord:
    build: ../SCMarketBot
    env_file: .env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: scmarket
      POSTGRES_DB: scmarket
      POSTGRES_PASSWORD: scmarket
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /var/lib/dashboard/postgresql/data_prodcopy:/var/lib/postgresql/data
    ports:
      - "5432:5432"