version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "7000:7000"
    networks:
      - default
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./ssh-keys:/etc/ssh/
    restart: unless-stopped

  discord:
    build: ../SCMarketBot
    env_file: .env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: scmarket
      POSTGRES_DB: scmarket
      POSTGRES_PASSWORD: scmarket
    volumes:
      - ./config/postgres/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /var/lib/dashboard/postgresql/data_prodcopy:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"