/**
 * Error Code Definitions
 *
 * Standardized error codes for API responses.
 * Maps to HTTP status codes and provides machine-readable error identification.
 */

export enum ErrorCode {
  // Client errors (4xx)
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // Server errors (5xx)
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  DATABASE_ERROR = "DATABASE_ERROR",

  // Business logic errors
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  ORDER_ALREADY_COMPLETED = "ORDER_ALREADY_COMPLETED",
  LISTING_ALREADY_SOLD = "LISTING_ALREADY_SOLD",
  INVALID_TRANSACTION = "INVALID_TRANSACTION",
  
  // Stock management errors
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
  INVALID_QUANTITY = "INVALID_QUANTITY",
  OVER_ALLOCATION = "OVER_ALLOCATION",
  CHARACTER_LIMIT_EXCEEDED = "CHARACTER_LIMIT_EXCEEDED",
  CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION",
}
